spring:
  rabbitmq:
    host: shared-platform-rabbitmq-cip
  application:
    name: shared-platform-order
  cloud:
    bus:
      trace:
        enabled: true
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
gyyx:
  test: abcaaaa