spring:
  cloud:
    consul:
      discovery:
        register: false
  application:
    name: shared-platform-order
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
